language: bash
services: docker

branches:
  only:
    - master

before_install:
  - shellcheck scripts/docker/* test/*.sh

install:
  - bash -x -e ./test/travis-ci-build.sh

script:
  - docker-compose --file "${TRAVIS_BUILD_DIR}/test/docker-composer.travis-ci.yml" --project-name test up &
  - bash -x -e ./test/travis-ci-run.sh
