language: php
services: docker
php: 7.3

cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"

branches:
  only:
    - master

env:
  matrix:
    - PROFILE="standard"
    - PROFILE="thunder"

before_install:
  - shellcheck scripts/docker/* test/*.sh

install:
  - bash -x -e ./test/travis-ci-build-${PROFILE}.sh

script:
  - docker-compose --file "${TRAVIS_BUILD_DIR}/test/docker-composer.${PROFILE}.yml" --project-name test up &
  - bash -x -e ./test/travis-ci-run.sh
