language: bash
services: docker

branches:
  only:
    - master

env:
  matrix:
    - PROFILE="standard"
    - PROFILE="thunder"

before_install:
  - shellcheck scripts/docker/* test/*.sh

install:
  - bash -x -e ./test/travis-ci-build.sh

script:
  - docker-compose --file "${TRAVIS_BUILD_DIR}/test/docker-composer.${PROFILE}.yml" --project-name test up &
  - bash -x -e ./test/travis-ci-run.sh
