#!/usr/bin/env bash

# Drupal core's docroot.
cd "${INSTALLATION_DIRECTORY}" || exit 1

# Thunder's docroot
[ -d "docroot" ] && cd docroot || exit 1

# Core recommended's docroot
[ -d "web" ] && cd web || exit 1

# Set up DOC_ROOT environment variable.
echo "Setting DOC_ROOT to $(pwd)"

{
    echo -e "\n";
    echo -e "export DOC_ROOT=\"$(pwd)\"\n";
    echo -e "\n";
} >> /home/thunder/.profile;
