#!/usr/bin/env bash
#
# Server and run Nightwatch JS Tests

cd ${DOC_ROOT} || exit 1

echo "Serving on: 0.0.0.0:8080 ..."
php --server 0.0.0.0:8080 .ht.router.php &

STATUS=$?
echo "Server started with status: ${STATUS}"
if [ "${STATUS}" != "0" ]; then
    echo "Failed to start '.ht.router.php': ${STATUS}"

    exit $STATUS
fi

echo "Wait for Drupal to be ready..."
while ! curl --output /dev/null --silent --head --fail "http://localhost:8080"; do
    sleep 1
done

cd ${DOC_ROOT}/core || exit 1

echo "Starting tests..."
yarn test:nightwatch --tag "${THUNDER_TEST_GROUP}"
