#!/usr/bin/env bash
#
# Server and run Nightwatch JS Tests

cd /home/thunder/www/docroot || exit 1

echo 'Serving on: 0.0.0.0:8080 ...'
php --server 0.0.0.0:8080 .ht.router.php &

STATUS=$?
if [ $STATUS -ne 0 ]; then
    echo "Failed to start '.ht.router.php': ${STATUS}"

    exit $STATUS
fi

while ! curl --output /dev/null --silent --head --fail http://localhost:8080; do
    sleep 1
done

cd /home/thunder/www/docroot/core || exit 1

yarn test:nightwatch --tag "${THUNDER_TEST_GROUP}"
