#!/bin/bash
#
# Install Thunder and run performance test

# Set all runtime environments for "thunder" user
echo -e "\n" >> /home/thunder/.profile;
echo -e "export DB_HOST=\"$DB_HOST\"\n" >> /home/thunder/.profile;
echo -e "export DB_NAME=\"$DB_NAME\"\n" >> /home/thunder/.profile;
echo -e "export DB_USER=\"$DB_USER\"\n" >> /home/thunder/.profile;
echo -e "export DB_PASS=\"$DB_PASS\"\n" >> /home/thunder/.profile;
echo -e "export DB_PORT=\"$DB_PORT\"\n" >> /home/thunder/.profile;
echo -e "export DB_DIVER=\"$DB_DIVER\"\n" >> /home/thunder/.profile;

echo -e "\n" >> /home/thunder/.profile;
echo -e "export THUNDER_HOST=\"$THUNDER_HOST\"\n" >> /home/thunder/.profile;
echo -e "export CHROME_HOST=\"$CHROME_HOST\"\n" >> /home/thunder/.profile;

echo -e "\n" >> /home/thunder/.profile;
echo -e "export ELASTIC_APM_URL=\"$ELASTIC_APM_URL\"\n" >> /home/thunder/.profile;
echo -e "export ELASTIC_APM_CONTEXT_TAG_BRANCH=\"$ELASTIC_APM_CONTEXT_TAG_BRANCH\"\n" >> /home/thunder/.profile;

# Build, install and serve Thunder
su - thunder -c "bash -x thunder-php-install && bash -x thunder-php-test"
