#!/bin/bash
#
# Install Thunder

# Add write for settings.php
chmod a+w /home/thunder/www/docroot/sites/default/settings.php

# Adjust settings.php
cat <<EOF >> /home/thunder/www/docroot/sites/default/settings.php

if (!isset(\$databases)) {
  \$databases = [];
}

\$databases['default']['default'] = [
  'prefix' => '',
];

EOF

HASH_SALT="$(openssl rand -hex 32)"
echo -e "\$settings['hash_salt'] = '${HASH_SALT}';\n\n" >> /home/thunder/www/docroot/sites/default/settings.php

echo -e "\$databases['default']['default']['host'] = '${DB_HOST}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['port'] = '${DB_PORT}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['database'] = '${DB_NAME}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['username'] = '${DB_USER}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['password'] = '${DB_PASS}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['namespace'] = 'Drupal\\Core\\Database\\Driver\\${DB_DIVER}';\n" >> /home/thunder/www/docroot/sites/default/settings.php
echo -e "\$databases['default']['default']['driver'] = '${DB_DIVER}';\n" >> /home/thunder/www/docroot/sites/default/settings.php

# Remove write for settings.php
chmod a-w /home/thunder/www/docroot/sites/default/settings.php

# Tweak .env file for testing
# .env file
cp /home/thunder/www/docroot/core/.env.example /home/thunder/www/docroot/core/.env
echo "DRUPAL_TEST_WEBDRIVER_CHROME_ARGS=\\\`--disable-gpu --headless --no-sandbox --disable-web-security\\\`" >> /home/thunder/www/docroot/core/.env
echo "DRUPAL_TEST_CHROMEDRIVER_AUTOSTART=false" >> /home/thunder/www/docroot/core/.env
echo "DRUPAL_TEST_WEBDRIVER_PORT=4444" >> /home/thunder/www/docroot/core/.env
echo "DRUPAL_TEST_WEBDRIVER_PATH_PREFIX=/wd/hub" >> /home/thunder/www/docroot/core/.env
echo "DRUPAL_TEST_BASE_URL=http://${THUNDER_HOST}:8080" >> /home/thunder/www/docroot/core/.env
echo "DRUPAL_TEST_DB_URL=mysql://thunder@${DB_HOST}:3306/thunder" >> /home/thunder/www/docroot/core/.env
echo "DRUPAL_TEST_WEBDRIVER_HOSTNAME=${CHROME_HOST}" >> /home/thunder/www/docroot/core/.env
echo "THUNDER_BRANCH=${ELASTIC_APM_CONTEXT_TAG_BRANCH}" >> /home/thunder/www/docroot/core/.env
echo "THUNDER_SITE_HOSTNAME=${THUNDER_HOST}" >> /home/thunder/www/docroot/core/.env
echo "THUNDER_APM_URL=${ELASTIC_APM_URL}" >> /home/thunder/www/docroot/core/.env

# Install and enable required modules
cd /home/thunder/www/docroot

# Wait for database to be awailable
while drush --quiet sql:query "SELECT 1 FROM DUAL;"; do
    sleep 5
done

drush -y si thunder --debug
drush -y en thunder_performance_measurement --debug
drush cr
